### ISSUE TITLE
JSONPath-plus support

### ISSUE THREAD

**Issue by pavelkornev** [P0lip/nimma#2]
Hi Jakub!

In the README there is a statement:
```
Supports the majority of JSONPath-plus additions
```

Is there a list of supported features?

I've tried to use things like `@root`, `@parent` — it doesn't work for me... does Nimma support them?

**Comment by P0lip** [comment]
Hey!
It should be supported, albeit it depends on how complex the JSONPath is.
If it's complex, you may need to initialize Nimma with `unsafe` flag.
Alternatively, you can take the Spectral approach -> https://github.com/stoplightio/spectral/blob/36ec40e92abb6fe0ffbc104722599147dda555fb/packages/core/src/runner/runner.ts#L98
