### ISSUE TITLE
Extension for @jsep-plugin/arrow

### ISSUE THREAD

**Issue by rguttroff** [P0lip/nimma#3]
Hi Jakub,

I use filter expressions to search for an entry in an array of objects. Is it possible for you to include the @jsep-plugin/arrow? For example, the Array.find() method can also be used as a filter expression in the array.

Here is a small example:

JSONPath: `$[?(@.phoneNumbers && @.phoneNumbers.find(phoneNumber => phoneNumber.type.match(/iPh.*/)))]`

`[{
    "firstName": "John",
    "lastName": "doe",
    "age": 26,
    "address": {
        "streetAddress": "naist street",
        "city": "Nara",
        "postalCode": "630-0192"
    },
    "phoneNumbers": [
        {
            "type": "iPhone",
            "number": "0123-4567-8888"
        },
        {
            "type": "home",
            "number": "0123-4567-8910"
        }
    ]
}]`

Best regards,
Rainer

**Comment by P0lip** [comment]
Hey!
I'm hesitant to support it out of the box as this wouldn't be particularly compatible with other implementations of JSONPath expressions, however, I could expose an option to register custom jsep plugins.
Would that be something matching your needs?

**Comment by rguttroff** [comment]
Hi,

actually I have the problem with stoplightio/spectral that my JSONPath is not supported by nimma. If the plugin is generally available, then no adjustments are necessary there. But I can understand your concerns. Your suggestion will help and I can post another feature request at stoplightio/spectral, if the option is available.

**Comment by P0lip** [comment]
@rguttroff I'm not sure if that helps, but I forgot to mention that the JSON Path expression you posted can be somewhat translated into something Nimma understands. `$.phoneNumbers[?(@.type ~= "iPh.*")]^^` will yield similar results as the JSON Path expression you posted.

**Comment by rguttroff** [comment]
@P0lip Nice. That would work. I still need to partially access a subpath. Here the output path seems to diverge between the solutions. Spectrale also has its difficulties with this. Is this a bug?

Example JSON:
```json
[{
    "firstName": "John",
    "lastName": "doe",
    "age": 26,
    "address": {
        "streetAddress": "naist street",
        "city": "Nara",
        "postalCode": "630-0192"
    },
    "phoneNumbers": [
        {
            "type": "iPhone",
            "number": "0123-4567-8888"
        },
        {
            "type": "home",
            "number": "0123-4567-8910"
        }
    ]
}]
```

<table>
<tr>
<td></td>
<td> <strong>Filter with .find()</strong> </td> <td> <strong>Filter with parent expression</strong> </td>
</tr>
<tr>
<td> <strong>JSONPath</strong> </td>
<td>

`$[?(@.phoneNumbers && @.phoneNumbers.find(phoneNumber => phoneNumber.type.match(/iPh.*/)))]`

</td>
<td>

`$..phoneNumbers[?(@.type == "iPhone")]^^^.address`

</td>
</tr>
<tr>
<td> <strong>Result</strong> </td>
<td> 

```json
[
  {
    "streetAddress": "naist street",
    "city": "Nara",
    "postalCode": "630-0192"
  }
]
```

</td>
<td>

```json
[
  {
    "streetAddress": "naist street",
    "city": "Nara",
    "postalCode": "630-0192"
  }
]
```

</td>
</tr>
<tr>
<td> <strong>Output paths</strong> </td>
<td> 

```json
[
  "$[0]['address']"
]
```

</td>
<td>

```json
[
  "$['address']"
]
```

</td>
</tr>
</table>

**Comment by P0lip** [comment]
Yeah, it looks like a bug to me, although not in `nimma` itself, since I didn't support for such JSONPath expressions.

Speaking of Spectral, you can use `field` on `then` if you need to access `address`.

```json
"given": "$.phoneNumbers[?(@.type ~= 'iPh.*')]^^"
"then": {
  "field": "address"
}
```

This should do the trick

**Comment by rguttroff** [comment]
Thanks. It is working.
